"""add resume_text column to resumes

Revision ID: de54b0773068
Revises: 31629fcd70e1
Create Date: 2026-07-30 17:22:07.061967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de54b0773068'
down_revision: Union[str, Sequence[str], None] = '31629fcd70e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('resume_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'resume_text')
    # ### end Alembic commands ###
